# generated from catkin/cmake/template/pkg-config.cmake.in

# append elements to a list if they are not already in the list
# copied from catkin/cmake/list_append_unique.cmake to keep pkgConfig
# self contained
macro(_list_append_unique listname)
  foreach(_item ${ARGN})
    list(FIND ${listname} ${_item} _index)
    if(_index EQUAL -1)
      list(APPEND ${listname} ${_item})
    endif()
  endforeach()
endmacro()

# remove duplicate libraries, generalized from PCLConfig.cmake.in
macro(_remove_duplicate_libraries _unfiltered_libraries _final_filtered_libraries)
  set(_filtered_libraries)
  set(_debug_libraries)
  set(_optimized_libraries)
  set(_other_libraries)
  set(_waiting_for_debug 0)
  set(_waiting_for_optimized 0)
  set(_library_position -1)
  foreach(library ${${_unfiltered_libraries}})
    if("${library}" STREQUAL "debug")
      set(_waiting_for_debug 1)
    elseif("${library}" STREQUAL "optimized")
      set(_waiting_for_optimized 1)
    elseif(_waiting_for_debug)
      list(FIND _debug_libraries "${library}" library_position)
      if(library_position EQUAL -1)
        list(APPEND ${_filtered_libraries} debug ${library})
        list(APPEND _debug_libraries ${library})
      endif()
      set(_waiting_for_debug 0)
    elseif(_waiting_for_optimized)
      list(FIND _optimized_libraries "${library}" library_position)
      if(library_position EQUAL -1)
        list(APPEND ${_filtered_libraries} optimized ${library})
        list(APPEND _optimized_libraries ${library})
      endif()
      set(_waiting_for_optimized 0)
    else("${library}" STREQUAL "debug")
      list(FIND _other_libraries "${library}" library_position)
      if(library_position EQUAL -1)
        list(APPEND ${_filtered_libraries} ${library})
        list(APPEND _other_libraries ${library})
      endif()
    endif("${library}" STREQUAL "debug")
  endforeach(library)
  set(_final_filtered_libraries _filtered_libraries)
endmacro()


if(roslisp_CONFIG_INCLUDED)
  return()
endif()
set(roslisp_CONFIG_INCLUDED TRUE)

# flag project as catkin-based to distinguish if a find_package()-ed project is a catkin project
set(roslisp_FOUND_CATKIN_PROJECT TRUE)

if(NOT "X" STREQUAL "X")
  set(roslisp_INCLUDE_DIRS "")
  foreach(idir )
    if(IS_ABSOLUTE ${idir} AND IS_DIRECTORY ${idir})
      set(include ${idir})
    elseif(IS_DIRECTORY /opt/ros/groovy/${idir})
      set(include /opt/ros/groovy/${idir})
    else()
      message(FATAL_ERROR "Project 'roslisp' specifies '${idir}' as an include dir, which is not found.  It does neither exist as an absolute directory nor in '/opt/ros/groovy/${idir}'.  Ask the maintainer '${roslisp_MAINTAINER}' to fix it.")
    endif()
    _list_append_unique(roslisp_INCLUDE_DIRS ${include})
  endforeach()
endif()

foreach(library )
  if(NOT TARGET ${library})
    set(lib_path "")
    set(lib "${library}-NOTFOUND")
    # since the path where the library is found is returned we have to iterate over the paths manually
    foreach(path /opt/ros/groovy/lib;/opt/ros/groovy/lib)
      find_library(lib ${library}
        PATHS ${path}
        NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
      if(lib)
        set(lib_path ${path})
        break()
      endif()
    endforeach()
    if(lib)
      _list_append_unique(roslisp_LIBRARY_DIRS ${lib_path})
      list(APPEND roslisp_LIBRARIES ${lib})
    else()
      # as a fall back for non-catkin libraries try to search globally
      find_library(lib ${library})
      if(NOT lib)
        message(FATAL_ERROR "Project '${PROJECT_NAME}' tried to find library '${library}'.  The library is neither a target nor built/installed properly.  Did you compiled project 'roslisp'?  Did you find_package() it before the subdirectory containing its code is included?")
      endif()
      list(APPEND roslisp_LIBRARIES ${lib})
    endif()
  else()
    list(APPEND roslisp_LIBRARIES ${library})
  endif()
endforeach()

foreach(dep )
  if(NOT ${dep}_FOUND)
    find_package(${dep})
  endif()
  _list_append_unique(roslisp_INCLUDE_DIRS ${${dep}_INCLUDE_DIRS})
  list(APPEND roslisp_LIBRARIES ${${dep}_LIBRARIES})
  _list_append_unique(roslisp_LIBRARY_DIRS ${${dep}_LIBRARY_DIRS})
endforeach()

if(roslisp_LIBRARIES)
  _remove_duplicate_libraries(roslisp_LIBRARIES roslisp_LIBRARIES)
endif()

foreach(extra roslisp-extras.cmake)
  include("/opt/ros/groovy/share/roslisp/cmake/${extra}")
endforeach()
